Вывод динамического каталога через JS, реализация модального окна с динамическими данными
snakeshaker/Kolesa-Upgrade-FE-2021 pull request #5
Opened 2021-10-10 21:39 UTC by snakeshaker

2021-10-11 04:27 UTC, kerim1505k commented on src/js/main.js
> +            });
У тебя здесь идет дублирование кода, что является плохой практикой. Вынеси реализацию в отдельную функцию.

2021-10-11 04:30 UTC, kerim1505k commented on src/js/main.js
> +document.body.addEventListener('change', (e) => {
Зачем вешать функцию на весь body, добавь слушатель только на необходимые элементы, в твоем случае это label`ы

2021-10-11 04:32 UTC, kerim1505k commented on src/js/main.js
> +    const cardCreate = addItem(isNew, title, price, img, isClothes, id);
Нужно проверять или сетить дефолтные значения данным, которые приходят с "бэкенда". У тебя статичный замоканный массив и ты уверен в наличии данных, но на реальных проектах есть вероятность отсутствия тех или иных параметров.

2021-10-11 04:34 UTC, kerim1505k commented on src/js/main.js
> +        <img class="js__img" src="${img}" alt="item" width="330" height="330">
В случае если у тебя не будет img в параметрах функции, то у тебя коряво отобразится верстка. Классно было бы заиметь какую-то заглушку для карточек, если товара вдруг нет, чтобы верстка была красивой. Можешь поискать в интернете какую-нибудь подобную заглушку
![image](https://user-images.githubusercontent.com/44666463/136733737-f519da19-ab91-4170-91fc-ac652966c93f.png)

2021-10-11 04:36 UTC, kerim1505k commented on src/js/main.js
> +        allItems.unshift(allItems.splice(i, 1)[0]);
Можно вынести в отдельную функцию сортировку "новых" товаров и просто передавать ей в каком массиве это нужно сделать.

2021-10-11 04:37 UTC, kerim1505k commented on src/js/main.js
> +const clothes = [
Не критично, но классно было бы вынести массивы мок данных в отдельные файлы и импортировать их сюда, чтобы в будущем можно было бы заюзать их где-то еще.

2021-10-11 04:38 UTC, kerim1505k commented on src/js/main.js
> +    modalContainer.innerHTML = `<div class="card">
Нужна проверка на наличие modalContainer

2021-10-11 04:42 UTC, kerim1505k commented on src/js/main.js
> +document.addEventListener('click', (e) => {
Вешаешь слушатель на весь документ, хотя логика завязана только на карточке. Поменяй элемент слушателя на нее.

2021-10-11 04:44 UTC, kerim1505k commented on src/js/main.js
> +        hasClass(e.target, 'js__img')
Очень сложная конструкция. По сути у тебя открытие модалки происходит по клику на всю карточку, поэтому тебе надо повешать слушатель на всю ее доступную площадь и кнопку (когда ее видно). Тогда тебе не надо будет проверять каждую деталь внутри карточки, как ты делаешь сейчас.

2021-10-11 04:48 UTC, kerim1505k commented on src/js/main.js
> +    newDiv.classList.add(`${id}`);
Попробуй не просто передавать id в класс, а сделай типа js__catalog-item-${id}

2021-10-11 04:55 UTC, kerim1505k commented on src/js/main.js
> +            if (e.target.closest('.catalog__item').classList.contains(allItems[i].id)) {
Плохой селектор e.target.closest('..'), не совсем надежный.

Тебе нужно выбрать все карточки на странице, как это сделать, думаю ты знаешь.
Так как карточек несколько, это скорее всего будет массив. Пройдись методом перебора по массиву и на каждый элемент массива (каждая карточка) повешай слушатель. Там вверху где ты добавляешь айди в класс, ты можешь запихать его в дата атрибуты и далее использовать его для поиска в массиве.

2021-10-11 04:56 UTC, kerim1505k commented on src/js/main.js
> +function changeModal(title, price, img, isClothes, details) {
Как описывал выше, этих элементов может и не быть в реальных проектах. Поэтому нужны либо какие-то заглушки, либо проверки на их наличие.

2021-10-11 04:58 UTC, kerim1505k commented on src/js/main.js
> +const modalContainer = document.querySelector('.card-container');
Не критично, но лучше описывать какие-то глобальные вещи, которые затем используются по всему файлу, в самом начале файла.
```
import 'something' from 'somewhere';

const modalContainer = ...;
const GLOBAL_CONST = 'something';
const TIMEOUT = 60;

function doSomething() {
   // do stuff
}
```
и т.д

2021-10-11 05:01 UTC, kerim1505k commented on src/js/main.js
> +    document.querySelector('.js__catalog').append(cardCreate);
Ты много где используешь document.querySelector('.js__catalog'). Вынеси ее в константу наверх и используй ее.

2021-10-11 05:01 UTC, kerim1505k commented on src/js/main.js
> +    document.querySelector('.js__catalog').append(cardCreate);
Плюс нужна проверка этого элемента

2021-10-11 05:01 UTC, kerim1505k commented on src/js/main.js
> +    const newDiv = document.createElement('DIV');
newDiv может и не создаться, нужна проверка после :)

2021-10-11 05:04 UTC, kerim1505k requested changes
Есть места для улучшения

2021-10-11 05:08 UTC, kerim1505k commented on src/js/main.js
> +    newDiv.classList.add(`${id}`);
Либо засунь айди карточки в data-attributes и используй их там.

2021-10-11 07:35 UTC, adlbk commented on src/js/main.js
> +document.body.addEventListener('change', (e) => {
Исправил, но в моем случае это оказались input`ы :) При проверке через click handler, в консоль выводит именно input

2021-10-11 13:26 UTC, snakeshaker commented on src/js/main.js
> +            if (e.target.closest('.catalog__item').classList.contains(allItems[i].id)) {
У меня при попытке реализации таким образом при смене вкладки(все товары/одежда/аксессуары) переставали работать ивент слушатели и модалка не открывалась, помогала лишь перезагрузка страницы. Вместо этого решил использовать event delegation и поставил слушатель на сам каталог (т.е. родитель который статичен), где .closest() вполне надежный и как я узнал такая конструкция является одним из основных решений. Если по вашему это ошибка или недочёт то почему? Я честно говоря для себя другого адекватного варианта не нашел.

2021-10-12 03:13 UTC, kerim1505k commented on src/js/main.js
> +            if (e.target.closest('.catalog__item').classList.contains(allItems[i].id)) {
```
const allCards = document.querySelectorAll('.catalog__item');

allCards.forEach(card => {
     card.addEventListener('click', () => {
          const { id: cardId } = card.dataset;
          
          const cardData = allItems.filter(item => item[id] === cardId);
          
          changeModal(cardData);
     });
});

```

Примерно так

2021-10-12 03:17 UTC, kerim1505k approved these changes

2021-10-12 07:47 UTC, snakeshaker commented on src/js/main.js
> +            if (e.target.closest('.catalog__item').classList.contains(allItems[i].id)) {
блин я даже не знал что можно через такой метод сделать :) Спасибо!

2021-10-12 07:47 UTC, merged