Рефактор проекта на Vue.js
snakeshaker/Kolesa-Upgrade-FE-2021 pull request #6
Opened 2021-10-19 22:55 UTC by adlbk

2021-10-20 03:47 UTC, kerim1505k commented on vue-kolesa-upgrade/src/App.vue
> +<div class="content-container">
Отступ поехал

2021-10-20 03:48 UTC, kerim1505k commented on vue-kolesa-upgrade/src/App.vue
> +              </div>
Что-то с отступами, нечитабельно стало.

2021-10-20 03:49 UTC, kerim1505k commented on vue-kolesa-upgrade/src/App.vue
> +                <label for="item_all">Все товары</label>
Для фильтров товара в ДЗ указано использовать v-for, здесь его что-то не нашел :)

2021-10-20 03:52 UTC, kerim1505k commented on vue-kolesa-upgrade/src/App.vue
> +    sortedAll() {
Есть такой принципе в программировании DRY (Don't Repeat Yourself). Тут три строчки кода делают одно и тоже, меняется только массив. Можно вынести сортировку в отдельную функцию, а массив передавать как аргумент.

2021-10-20 03:54 UTC, kerim1505k commented on vue-kolesa-upgrade/src/App.vue
> +    openModal() {
```
toggleModal() {
    this.isShowModal = !this.isShowModal;
}

```

выглядит элегантнее

2021-10-20 03:57 UTC, kerim1505k requested changes
Не учел некоторые требования ДЗ.

2021-10-20 06:15 UTC, adlbk commented on vue-kolesa-upgrade/src/App.vue
> +    openModal() {
Никогда до этого не использовал такую конструкцию, забавно выглядит :)

2021-10-20 16:59 UTC, adlbk commented on vue-kolesa-upgrade/src/App.vue
> +              <div
Активный класс для выбранной категорий через “:class” я не делал, так как у меня радио кнопки и стили для активных кнопок у меня общие, не связанные с каким либо классом (input[checked]). В примерах показывали на button элементах, там это точно нужно. Такой принцип я реализовал на боковом меню (доп. задание)

2021-10-21 03:10 UTC, kerim1505k commented on vue-kolesa-upgrade/src/App.vue
> +                <label v-if="tab === 'Аксессуары'" for="item_accessories">Аксессуары</label>
```
<div
  v-for="(tab, index) in filterTabs"
  :key="index"
  class="main__filter-radio"
>
  <input
      @click="renderAll"
      class="js__filter"
      type="radio"
      id="tab.id"
      name="item-selector"
      checked
    >
    <label for="item.id">{{ tab }}</label>
</div>
```

Можно обойтись без условий v-if="tab === '...'" если обогатить массив нужными данными.

(не критично)

2021-10-21 03:11 UTC, kerim1505k approved these changes

2021-10-21 05:41 UTC, merged