Разделение на Vue компоненты, связь с Backend
snakeshaker/Kolesa-Upgrade-FE-2021 pull request #7
Opened 2021-10-26 21:55 UTC by adlbk

2021-10-27 06:43 UTC, kerim1505k commented on vue-kolesa-upgrade/src/components/sideNavigation.vue
> +            Kolesa <span class="aside__nav--bold">Team</span>
Можно сделать короче и не создавать условий. Принцип DRY (Don't Repeat Yourself) в программировании. У тебя единственное различие это в жирности ссылки.

2021-10-27 06:46 UTC, kerim1505k commented on vue-kolesa-upgrade/src/components/CatalogFilter.vue
> +        tab.id == 'item_all' ?
Очень длинное тернарное условие, лучше создать метод, который будет возвращать тебе необходимое в зависимости от переданного tab.id.

2021-10-27 06:48 UTC, kerim1505k commented on vue-kolesa-upgrade/src/components/CatalogItem.vue
> +        :src="item.mainImage ?
```
item.mainImage || require('@/assets/img/no-photo.jpg')
```

2021-10-27 06:53 UTC, kerim1505k commented on vue-kolesa-upgrade/src/components/Modal.vue
> +                Попросить {{ lowBalance() }} баллов
lowBalance() больше похоже на вычисляемое (computed) свойство, чем на метод.

2021-10-27 06:57 UTC, kerim1505k commented on vue-kolesa-upgrade/src/App.vue
> +  created() {
Лайфхуки нужно описывать перед методами.

2021-10-27 07:09 UTC, kerim1505k approved these changes
Хорошо справился с заданием, большинство моих комментариев некритичные, просто пытаюсь донести до тебя важность элегантности кода.
Единственное, что смущает, то что ты не отображаешь сразу все товары и появляются они только по клику. Мне изначально как юзеру было не совсем понятно это, показалось что никаких товаров нет, пока я не кликнул. Фронтендер должен думать о понятном и доступном интерфейсе для юзеров (UI/UX) :) Ставлю апрув, замержишь когда надо будет.

P.S. Еще круто было бы подумать насчет лоудера или скелетона для карточек, пока ждем ответ с сервера. Это не было в задаче, но если хочешь можешь сделать.

2021-10-27 14:40 UTC, adlbk commented on vue-kolesa-upgrade/src/components/CatalogFilter.vue
> +  },
У меня получилось сделать отрисовку элементов только таким образом (искусственный клик при загрузке). Так как в самом App.vue не получалось сделать это, выдавало undefined (Хотел вызвать метод renderAll в lifecycle в App.vue). Насколько это костыль? Может ли такой вариант решения считаться приемлемым или это уже ненужное усложнение? Я другого рабочего решения не нашел :(

2021-10-27 14:44 UTC, adlbk commented on vue-kolesa-upgrade/src/components/sideNavigation.vue
> +      ],
Тут я казалось бы значительно укоротил, сохранив функциональность. Но мне интересно насколько это правильно? Тут я поменял сам элемент массива чтобы был именно жирным, но кажется это далеко не best practice :) Был ли другой адекватный вариант? Я пытался сделать по-другому но стили сохранять не получалось (ссылка была как все, не жирной). Как по мне дополнительная сложность была в том что у меня там внутри есть спан

2021-10-28 03:36 UTC, kerim1505k commented on vue-kolesa-upgrade/src/App.vue
> +    }, (error) => Promise.reject(error));
Сложновато немного получается в итоге. Можно было бы в самом методе fetchInfo перед тем, как делать запрос на сервер, добавить эффект загрузки через твой класс catalog--loading. И в конце после успешного ответа и всех необходимых манипуляций убирать этот класс.

2021-10-28 03:39 UTC, kerim1505k commented on vue-kolesa-upgrade/src/App.vue
> +      axios.get('-_RLsEGjof6i/data')
На первый взгляд не совсем понятно. что это за два запроса. Можно было бы разделить их на две функции.

```
async fetchInfo() {
     await this.getAccessories();
     await this.getClothes();
}
```

Так сразу становится понятным, что происходит в этом методе.

2021-10-28 03:44 UTC, kerim1505k commented on vue-kolesa-upgrade/src/components/CatalogFilter.vue
> +  },
Внутри fetchInfo получить clothes и accessories, объединить их в массив allItems и вызвать renderAll. Внутри catalogFilter оставить все emit`ы как были.

2021-10-28 03:46 UTC, kerim1505k requested changes
Удали свой костыль в CatalogFilter, вызови renderAll после получения clothes и accessories внутри fetchInfo.

2021-10-28 03:49 UTC, kerim1505k commented on vue-kolesa-upgrade/src/components/sideNavigation.vue
> +      ],
Ладно, этот спан действительно чутка поднасрал нам логики. Можешь откатить до предыдущей версии как у тебя было.

2021-10-28 12:02 UTC, merged